staffapp/urls.py
from django.urls import path
from .views import UpdateEmployee, CreateEmployee, ViewEmployees, delete_employee

app_name = 'emp'
urlpatterns = [
    path('employee/edit/<int:pk>/', UpdateEmployee.as_view(), name='edit_employee'),
    path('employee/create/', CreateEmployee.as_view(), name='creating_employee'),
    path('employees/view/', ViewEmployees.as_view(), name='view_employees'),
    path('employees/view/ajax/delete/', delete_employee),
]

staffmanager/urls.py
from django.urls import path, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from staffmanager import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.redirect_employee),
    path('staff_management', views.redirect_employee),
    path('staff_management/', include('staffapp.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

staffapp/models.py
from django.db import models
from django.db.models.deletion import Collector
from django.db import router
from .common.util.system_operations import delete_image


class Employee(models.Model):
    employee_firstname = models.CharField(max_length=20, blank=False, unique=True)
    employee_surname = models.CharField(max_length=20, blank=False)
    employee_job_title = models.CharField(max_length=20, blank=False)
    date_started = models.DateField('Date started at Company', blank=False)
    job_description = models.TextField(max_length=70, default=None)
    employee_image = models.ImageField(upload_to="employee_images/", blank=True)

    def delete(self, using=None, keep_parents=False):

        if self.employee_image:
            image_url = self.employee_image.url
            image_path = image_url[image_url.find('/', 2):]
            delete_image(image_path=image_path)

        return super().delete(using, keep_parents)

staffapp/forms.py
from staffapp.models import Employee
import datetime
from django.utils import timezone
from django import forms
from .common.util.system_operations import delete_image


class EmployeeForm(forms.ModelForm):

    def clean(self):
        cd = super().clean()
        prev_image = self.instance.employee_image
        if 'employee_image' in cd:
            if (cd['employee_image'] is False and prev_image) or (cd['employee_image'] and prev_image):
                image_url = prev_image.url
                image_url = image_url[image_url.find('/', 2):]
                delete_image(image_path=image_url)

        future = timezone.now() + datetime.timedelta(days=1)
        date = cd.get('date_started')
        if str(date) >= str(future):
            self.add_error('date_started', "The date started value cannot be in the future! ...")
        return cd

    class Meta:
        model = Employee
        exclude = ()

staffapp/views.py
from django.views.generic import CreateView, UpdateView, ListView
from staffapp.forms import EmployeeForm
from staffapp.models import Employee
from django.http import JsonResponse


class ViewEmployees(ListView):
    template_name = 'employees/employees.html'
    context_object_name = 'staff_members'

    def get_queryset(self):
        return Employee.objects.all()


class CreateEmployee(CreateView):
    template_name = 'employees/employee_edit_form.html'
    form_class = EmployeeForm
    success_url = '/staff_management/employees/view'


class UpdateEmployee(UpdateView):
    template_name = 'employees/employee_edit_form.html'
    form_class = EmployeeForm
    success_url = '/staff_management/employees/view'

    def get_object(self, queryset=None):
        """
        Return the object the view is displaying.
        Require `pk` argument in the URLconf.
        """
        obj = Employee.objects.get(pk=self.kwargs.get(self.pk_url_kwarg))
        return obj


def delete_employee(request):
    """
    :param request: Used to retrieve the id of the employee to be deleted
    :return: returns a Json response on whether the deletion was a success or failure
    """
    action_id = request.POST.get('param_data[id]')
    try:
        result = Employee.objects.get(pk=action_id).delete()
    except Exception as e:
        print('Error: ', e)
        result = False
    return JsonResponse({'user_delete': result})

staffmanager/views.py
from django.shortcuts import redirect, reverse


def redirect_employee(request):
    """
    :param request:
    :return: Redirects the user to a valid page
    """
    return redirect(reverse('emp:view_employees'))

staffapp/templates/base.html
<html>
    <head>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
        {% load static %}
        <link rel="stylesheet" href="{% static 'management/css/style.css' %}" type="text/css">
        <script src="https://code.jquery.com/jquery-3.1.0.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/js-cookie@2/src/js.cookie.min.js"></script>
        {% block head %}
            <meta charset="UTF-8">
            <title>Employees Page</title>
        {% endblock %}
    </head>
    <br>
    {% block nav %}
        <div id="navbar" class="navbar-collapse collapse">
              <ul class="nav navbar-nav">
                <li><a href="{% url 'emp:view_employees' %}">Employees</a></li>
              </ul>
        </div>
    {% endblock %}
    <body>
        {% block body %}
        {% endblock %}
    </body>
</html>

staffapp/templates/employees/employee_edit_form.html
{% extends 'base.html' %}

{% block body %}
  <div class="container">
    <h1> Employee creation form </h1>

    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>

    <form method="post" enctype="multipart/form-data">
      {%csrf_token%}
      {{ form.as_p }}
      <button type="submit">Submit</button>
      <script>
        $( function() {
            $( "#id_date_started" ).datepicker({ dateFormat: 'yy-mm-dd' });
        });
      </script>
    </form>
  </div>
{% endblock %}

staffapp/templates/employees/employees.html
{% extends 'base.html' %}
{% csrf_token %}
{% block head %}
    <meta charset="UTF-8">
    <title>employee management</title>
{% endblock %}

{% block nav %}
  <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
          <li><a href="#">Employees</a></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
          <li><a href="{% url 'emp:creating_employee' %}">Add User</a></li>
      </ul>
  </div>
{% endblock %}

{% block body %}
  {% load static %}
  <script type="text/javascript" src="{% static 'management/js/jquery.sortElements.js' %} "></script>
  <script type="text/javascript" src="{% static 'management/js/employee_table.js' %} "></script>

  <div class="container">
    {% if staff_members %}
      <table id="DataTable" class="table table-striped table-bordered">
        <thead>
          <tr>
            <th id="name">Name</th>
            <th id="surname">Surname</th>
            <th id="job_title">Job title</th>
            <th id="start_date">Company Start Date</th>
            <th id="job_descrip">Job Description</th>
            <th id="avatar">Avatar</th>
            <th id="actions">Actions</th>
          </tr>
        </thead>

        <tbody>
          {% for member in staff_members %}
            <tr id="{{member.pk}}">
              <td>{{member.employee_firstname}}</td>
              <td>{{member.employee_surname}}</td>
              <td>{{member.employee_job_title}}</td>
              <td>{{member.date_started}}</td>
              <td>{{member.job_description}}</td>
              {% if member.employee_image %}
                <td><img src="{{member.employee_image.url}}" height="150" width="150"></td>
              {% else %}
                <td><img src="/static/default_images/default_avatar.jpg" height="150" width="150"></td>
              {% endif %}

              <td><button type="button" id="delete_{{member.pk}}">Delete User</button><br><a type="button" href="{% url 'emp:edit_employee' member.pk %}">Edit User</a>
            </tr>
          {% endfor %}
        </tbody>
      </table>
    {% else %}
      <h1>
        <p>No Staff Data available.</p>
      </h1>
    {% endif %}
  </div>
{% endblock %}